###Configuration file
#
## path to reads
reads : /projects/AusGEM/i3_genomes/Gulls_2018
#
##path to output directory:
output : /home/malcummi/Data/Manuscripts/Salmonella_Wollongong_2019_Gull/output/shovill
#
