configfile:
    "/home/malcummi/Data/pipelord/combined_config.yaml"
    #"/projects/AusGEM/Djordjevic_genomes/config.yaml"
sample_ids, = glob_wildcards(config['reads']+"/{sample}.R1.fastq.gz")
prefix = config['prefix']


print(sample_ids,)

rule all:
    input:
        expand(config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out", sample=sample_ids, prefix=prefix),
        expand(config['outdir']+"/{prefix}/shovill"+"/final_assemblies/{sample}.fasta", sample=sample_ids, prefix=prefix)


rule shovill:
    input:
        r1 = config['reads']+"/{sample}.R1.fastq.gz",
        r2 = config['reads']+"/{sample}.R2.fastq.gz"
    output:      
        directory(config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out")
    #log:
        #config['outdir']+"shovill"+"/logs/shovill{sample}.log"
    conda:
        "config/shovill.yaml"
    shell:
        """
        shovill --minlen 200 --outdir {output} --R1 {input.r1} --R2 {input.r2}
        """

rule rename:
    input:
        config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out"
    output:
        config['outdir']+"/{prefix}/shovill"+"/final_assemblies/{sample}.fasta"
    shell:
        "cp {input}/contigs.fa {output}"

