configfile: "misc/masterconfig.yaml"

sample_ids, = glob_wildcards(config['reads']+"/{sample}.R1.fastq.gz")
prefix = config['prefix']

logs = config['base_log_outdir']


print(sample_ids,)

rule all:
    input:
        expand(config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out", sample=sample_ids, prefix=prefix),
        expand(config['outdir']+"/{prefix}/shovill"+"/final_assemblies/{sample}.fasta", sample=sample_ids, prefix=prefix)


rule shovill_run:
    input:
        r1 = config['reads']+"/{sample}.R1.fastq.gz",
        r2 = config['reads']+"/{sample}.R2.fastq.gz"
    output:
        directory(config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out")
    log:
        config['base_log_outdir']+"/shovill/run"
    conda:
        "config/shovill.yaml"
    shell:
        """
        shovill --minlen 200 --outdir {output} --R1 {input.r1} --R2 {input.r2}
        """

rule rename:
    input:
        config['outdir']+"/{prefix}/shovill"+"/assemblies/{sample}.out"
    output:
        config['outdir']+"/{prefix}/shovill"+"/final_assemblies/{sample}.fasta"
    log:
        config['base_log_outdir']+"/shovill/rename"
    shell:
        "cp {input}/contigs.fa {output}"

