###Configuration file
#
## path to reads - do not end in a slash
reads : /projects/AusGEM/i3_genomes/UoW_Salmonella_all
#
##path to output directory - do not end in a slash:
output : /projects/AusGEM/Users/Max/Manuscripts/UoW_Salmonella_all/output/shovill
#
