import re
import subprocess
import os

configfile: "pipelord2.0/misc/masterconfig.yaml"

# Get raw_reads
sample_ids, = glob_wildcards(config['raw_reads']+"/{sample}.R1.fastq.gz")
prefix = config['prefix']

print(sample_ids)

# one rule to rule them all
rule all:
    input:
        expand(config['outdir']+"/{prefix}/fastp/{sample}.R1.fastq.gz",
               sample=sample_ids, prefix=prefix)


rule run_fastp:
    input:
        r1 = config['raw_reads']+"/{sample}.R1.fastq.gz",
        r2 = config['raw_reads']+"/{sample}.R2.fastq.gz"
    output:
        r1_filt = config['outdir']+"/{prefix}/fastp/{sample}.R1.fastq.gz",
        r2_filt = config['outdir']+"/{prefix}/fastp/{sample}.R2.fastq.gz",
        json = config['outdir']+"/{prefix}/fastp/{sample}.fastp.json",
        html = config['outdir']+"/{prefix}/fastp/{sample}.fastp.html"
    conda:
        "yamls/fastp.yaml"
    priority: 9
    shell:
        """
        fastp -i {input.r1} -I {input.r2} -o {output.r1_filt} -O {output.r2_filt} -j {output.json} -h {output.html}
        """
